name: Cron Job Test

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  test-cron:
    runs-on: ubuntu-latest  # Prefer Ubuntu for better compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Log File (Demo)
        run: echo "Cron ran at $(date)" >> cron-log.txt

      - name: Upload Log File via FTP
        uses: samkirkland/ftp-deploy-action@v4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/cron_test/  # Adjust to your server path
          include: 
            - cron-log.txt  # Ensure only this file gets uploaded
