name: Cron Job Test

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  test-cron:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a temporary directory and log file
        run: |
          mkdir upload-dir
          echo "Cron ran at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" >> cron_test/cron-log.txt
        shell: pwsh  # Ensure Windows compatibility

      - name: Upload Only cron-log.txt via FTP
        uses: samkirkland/ftp-deploy-action@v4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./cron_test/  # Upload only from this directory
          server-dir: /public_html/cron_test/  
